pair/board/urls.py
from django.urls import path
from . import views

# Create your views here.
app_name = "board"
urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<int:pk_>", views.detail, name="detail"),
    path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("edit/<int:pk_>", views.edit, name="edit"),
    path("delete/<int:pk_>", views.delete, name="delete"),
    path("update/<int:pk>", views.update, name="update"),
]

pair/pair/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("board.urls")),
]

pair/board/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pair/board/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from .models import Review

# 화면 template
def index(request):
    review = Review.objects.all()
    context = {
        "review": review,
    }
    return render(request, "board/index.html", context)


def detail(request, pk_):
    Review.objects.get(id=pk_)
    review = Review.objects.all()
    context = {"review": review}

    return render(request, "board/detail.html", context)


def new(request):

    return render(request, "board/new.html")


def edit(request, pk_):
    review_ = Review.objects.get(id=pk_)
    context = {
        "review": review_,
    }
    return render(request, "board/edit.html", context)


def create(request):
    content = request.GET.get("content")
    title = request.GET.get("title")
    Review.objects.create(content=content, title=title)

    context = {
        "content": content,
        "title": title,
    }

    return redirect("board:index")


def delete(request, pk_):
    Review.objects.get(id=pk_).delete()

    return redirect("board:index")


def update(request, pk):
    review = Review.objects.get(id=pk)

    # 데이터를 받아오고
    title_ = request.GET.get("title")
    content_ = request.GET.get("content")

    # 데이터를 수정
    review.title = title_
    review.content = content_

    # 데이터를 수정한 것을 반영한다.
    review.save()

    return redirect("board:index")

pair/board/templates/board/detail.html
{% extends 'base.html' %}

{% block content %}
{% for re in review %}
<h3>제목 : {{re.title}}</h3>
<span>{{re.content}}</span>
<p class="mb-2 mt-2"><a href=" {% url 'board:edit' re.id %}">리뷰 수정</a>
  <a href="{% url 'board:delete' re.id%}">리뷰 삭제</a>
</p>
{% endfor %}
{% endblock %}

pair/board/templates/board/edit.html
{% extends 'base.html' %}


{% block content %}
<form action="{% url 'board:update' review.id%}">
  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">제목</label>
    <input type="text" class="form-control" id="" name="title" value="{{review.title}}">
  </div>
  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">내용</label>
    <textarea class="form-control" type="text" id="" name="content" rows="3">{{review.content}}</textarea>
  </div>
  <div class="input-group flex-nowrap ">
    <input type="submit" value="리뷰 수정" class="btn btn-primary form-control border-primary text-light"
      placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping">
  </div>
</form>
{% endblock %}

pair/board/templates/board/index.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'board:new'%}">리뷰 작성</a>
<form action="">
  <table class="table">
    <thead>
      <tr class="bg-dark text-light">
        <th scope="col">리뷰 번호</th>
        <th scope="col">리뷰 제목</th>
        <th scope="col">작성 시간</th>
      </tr>
    </thead>
    <tbody>
      {% for review_ in review %}
      <tr>
        <th scope="row">{{review_.id}}</th>
        <td><a href="{% url 'board:detail' review_.id %}">{{review_.title}}</a></td>
        <td>{{review_.created_at}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</form>
{% endblock %}

pair/board/templates/board/new.html
{% extends 'base.html' %}


{% block content %}
<form action="{% url 'board:create' %}">
  <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">제목</label>
    <input type="text" class="form-control" id="" name="title">
  </div>
  <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">내용</label>
    <textarea class="form-control" type="text" id="" name="content" rows="3"></textarea>
  </div>
  <div class="input-group flex-nowrap ">
    <input type="submit" value="리뷰 쓰기" class="btn btn-primary form-control border-primary text-light"
      placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping">
  </div>
</form>
{% endblock %}

pair/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
    crossorigin="anonymous"></script>
</head>

<body>
  {% block content %}
  {% endblock %}
</body>

</html>